### ISSUE TITLE
Travel Desk Request questions reset app

### ISSUE THREAD

**Issue by dpdavids** [ytgov/travel-authorization#107]
**Describe the bug**
On submission of a travel desk request questions to a traveller, the application get's hung up and then resets it self with seed data.

**To Reproduce**
1. Create and get approval for a travel authorization (my travel request submit travel desk request button available)
2. Click on 'Submit Travel desk request'
3. Enter flights and hotel information
4. Submit to travel desk
5. Open Travel desk screen - select the travel desk request
6. enter a few questions
7. Click the "Send to traveler" button (no obvious action happens)
8. Click the "Sent to traveler" button again (the action circles appear over the button.
9. navigated to my travel request looking for notification that a question was submitted (nothing there)
10. navigated to  travel request (https://travel-auth-dev.ynet.gov.yk.ca/travel-request) see if there was something there but it just spun trying to load
11. after navigating away the seed data got reset (loosing requests and permissions).

FYI: my user is admin and td user

**Expected behavior**
on "Send to traveler" an email with a link to the application and a summary of questions to the traveler should be provided.  Should be a visual change  to the traveler's dashboard that outstanding questions from travel desk are available.  Add to my-travel-requests notification that questions

**Comment by klondikemarlen** [comment]
[logs, travel-authorization, 2024-07-24.txt](https://github.com/user-attachments/files/16382208/logs.travel-authorization.2024-07-24.txt)

Log of crash provided by @etmayes5.

**Comment by klondikemarlen** [comment]
Experience will be improved by https://github.com/icefoganalytics/travel-authorization/issues/72, so I'm going to do that first.

**Comment by klondikemarlen** [comment]
Data wipe will be fixed by https://github.com/ytgov/travel-authorization/pull/117

**Comment by dpdavids** [comment]
appears fixed
