### ISSUE TITLE
PreApprove: Missing submission buttons

### ISSUE THREAD

**Issue by dpdavids** [ytgov/travel-authorization#108]
**Describe the bug**
As pat_admin or admin I expect to see a button to "submit my pre approved travel requests" and "print" on the top right of the preapproved travel grid (https://travel-auth-dev.ynet.gov.yk.ca/preapproved).  I am unable to see these buttons.

**To Reproduce**
1. Go to '(https://travel-auth-dev.ynet.gov.yk.ca/preapproved)'

**Expected behavior**
I would expect to see the additional buttons to continue with the process.

**Screenshots**
![image](https://github.com/user-attachments/assets/6db26d99-b81f-49a4-8a1a-ff6f747e264a)
expected buttons
![image](https://github.com/user-attachments/assets/5dce177a-4188-4b0e-9e30-b51adc7b8f8d)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - URL: https://travel-auth-dev.ynet.gov.yk.ca/preapproved
 - Version v2024.7.23.1

**Comment by klondikemarlen** [comment]
@dpdavids For future context, what does a pat_admin stand for? i.e. what should it show up in the UI as?
Is it a "Pre-Approved Travel Admin"? Or something like that?

**Comment by dpdavids** [comment]
This looks to be resolved.

**Comment by klondikemarlen** [comment]
If this is complete, would you mind closing the issue? I don't have edit rights to close issues created by you (since I'm not an edit level user for ytgov).
