### ISSUE TITLE
PreApproved: download to excel 

### ISSUE THREAD

**Issue by dpdavids** [ytgov/travel-authorization#94]
Relates to:
PreApproved Request download excel

# Context

**Is your feature request related to a problem? Please describe.**
Updates to Submission Request not showing

**Describe the solution you'd like**

- [ ] Preapproved Travel "export to excel" fields not populating properly

**Comment by klondikemarlen** [comment]
Oops, didn't see this one. Fixed in https://github.com/icefoganalytics/travel-authorization/pull/197 (https://github.com/ytgov/travel-authorization/pull/101)
The CSV headers didn't align with the object keys, and so information was all "undefined".

**Comment by dpdavids** [comment]
Appears to be resolved.
