### ISSUE TITLE
PreApproved: Submission not working properly

### ISSUE THREAD

**Issue by dpdavids** [ytgov/travel-authorization#96]
Relates to:
- TODO

# Context

**Is your feature request related to a problem? Please describe.**
on the request tab. Selected all (2) the requests I wanted to include in my submission. Selected "Submit Selected Travel" and hit save.  The submissions got moved over to the submission tab.  But only one of the two requests came over.  

**Describe the solution you'd like**
I want both selected requests to be included in the submissions.

**Comment by dpdavids** [comment]
![image](https://github.com/ytgov/travel-authorization/assets/89539008/71356d1d-41d0-44cc-bb4f-5eecd7ca8dde)
![image](https://github.com/ytgov/travel-authorization/assets/89539008/563f3c16-89e2-4bdd-b830-19dfb71a1651)

![image](https://github.com/ytgov/travel-authorization/assets/89539008/8b79eeec-28d5-426d-9252-72ef0de83455)
Submission date is wrong I made a submission June 13, 2024 and June 12, 2024
Location should have a comma seperate list of locations of all the request selected
![image](https://github.com/ytgov/travel-authorization/assets/89539008/d1c95ac7-c45a-4da3-92dc-2bec37e96a3d)
The print button shows that only 1 of the 3 requests were submitted.
![image](https://github.com/ytgov/travel-authorization/assets/89539008/84dc446f-3269-4b4d-9732-1b035a9e304f)
only shows 1 of 3 requests submitted

**Comment by klondikemarlen** [comment]
Page load failure identified as user lookup being commented out in a very large commit https://github.com/icefoganalytics/travel-authorization/commit/074a3fffc8b480551996815d413113f7b70b6b71#diff-242054ea7b3a9a1378bc22fcc6e3a2eb677978e3a182e6469d784bf37ee7c95c

**Comment by klondikemarlen** [comment]
Identified further issues do to data modeling mismatch.
Relationship between `preapprovedSubmissions` and `travel_authorization_pre_approvals` is one to many not one to one.

**Comment by klondikemarlen** [comment]
UI changes referring to .preApproval as singular need to be reverted; one example is https://github.com/icefoganalytics/travel-authorization/commit/dc55491d934aad0bef555f1dde7e11c2d39507d6. Probably other similar issues in https://github.com/icefoganalytics/travel-authorization/pull/179.

**Comment by klondikemarlen** [comment]
Identified issue with submission date being incorrect introduced in https://github.com/ytgov/travel-authorization/commit/98f86b1134b2650a23ec315566955bfc23a21670. Migrating sets default date to date that the migration ran at, rather than `CURRENT_TIMESTAMP`.

This issue was probably suppressed by someone manually setting `submittedDate` on submission; although, I can't find where after digging through the git history. Or maybe by us regularly dropping the database in production?
